name: test_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  flutter_native_splash: ^2.3.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF"  # Color de fondo del Splash Screen
  image: assets/images/Logo.png  # Imagen que se mostrar√° en el centro
  android: true
  ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf

  assets:
    - assets/images/banner.png
    - assets/images/maquinaria.png
    - assets/images/limpieza.png
    - assets/images/plantas.png
    - assets/images/jardineria.png
    - assets/images/Logo.png
    - assets/images/bannerCarrousel.png
